In [ ]:
import pandas as pd
import numpy as np

df_uncleaned = pd.read_csv('../Datasets/amazon_products_sales_data_uncleaned.csv')
df_uncleaned.head(1)

In [2]:
df_uncleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  object
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  30926 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: object(16)
memory usage: 5.2+ MB

In [3]:
df_uncleaned['rating'] = df_uncleaned.rating.str[0:3].astype(float)

In [4]:
df_uncleaned['bought_in_last_month'] = df_uncleaned['bought_in_last_month'].str.replace("+ bought in past month","").str.strip().str.replace("K","000")

In [5]:
df_uncleaned['bought_in_last_month'] = (
    df_uncleaned['bought_in_last_month']
    .where(df_uncleaned['bought_in_last_month'].str.isdigit(), np.nan)
    .astype('Int64')  # Use nullable integer type to allow NaNs
)

In [6]:
df_uncleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      32164 non-null  Int64
 4   current/discounted_price  30926 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: Int64(1), float64(1), object(14)
memory usage: 5.3+ MB

# Price on variant

price on variant tiene errores en los textos, cogemos el valor tras ":" en aquellos que contienen el carácter "$". Aquellos que no tengan "$", serán nulos

In [7]:
df_uncleaned['price_on_variant'] = df_uncleaned['price_on_variant'].str.split(":").str.get(1)

In [8]:
df_uncleaned.loc[~df_uncleaned['price_on_variant'].str.contains(r'\$', na=False), 'price_on_variant'] = np.nan

In [9]:
df_uncleaned['price_on_variant'] = df_uncleaned['price_on_variant'].str.strip().str.split(" ").str.get(0)

# CURRENT/DISCOUNTED_PRICE

In [10]:
df_uncleaned['current/discounted_price'] = df_uncleaned['current/discounted_price'].fillna(df_uncleaned['price_on_variant'])

In [11]:
df_uncleaned['current/discounted_price'] = df_uncleaned['current/discounted_price'].str.replace(r"\$", "", regex=True).str.replace(r",", "").astype(float)

# LIST_PRICE

In [12]:
df_uncleaned['listed_price'] = df_uncleaned['listed_price'].str.replace("$","").str.replace(",","").str.strip()

In [13]:
df_uncleaned['listed_price'].replace("No Discount", np.nan, inplace=True)

C:\Users\diego\AppData\Local\Temp\ipykernel_11156\490008601.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_uncleaned['listed_price'].replace("No Discount", np.nan, inplace=True)

In [14]:
df_uncleaned['listed_price'].fillna(df_uncleaned['current/discounted_price'], inplace=True)

C:\Users\diego\AppData\Local\Temp\ipykernel_11156\2846556854.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_uncleaned['listed_price'].fillna(df_uncleaned['current/discounted_price'], inplace=True)

In [15]:
df_uncleaned['listed_price'] = df_uncleaned['listed_price'].astype(float)

In [16]:
df_uncleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      32164 non-null  Int64
 4   current/discounted_price  40613 non-null  float64
 5   price_on_variant          20071 non-null  object
 6   listed_price              40613 non-null  float64
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: Int64(1), float64(3), object(12)
memory usage: 5.3+ MB

# IS_COUPONED

#### Haremos dos características
- is_couponed : 0/1 
- discount_coupon : valor del descuento (tenemos cupones con porcentajes y con valores de descuento)

In [17]:
df_uncleaned['has_coupon'] = np.where(df_uncleaned['is_couponed'] != 'No Coupon', 1, 0)
df_uncleaned.head()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at,has_coupon
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300,89.68,NaN,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29,1
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,"2,457",6000,9.99,NaN,15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29,0
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,"3,044",2000,314.00,NaN,349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29,0
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,"35,882",10000,162.24,$162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29,0
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,"28,988",10000,72.74,$72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29,0

# BUY_BOX_AVAILABILITY
Convertimos la columna a binaria, 1 si tiene "Add to cart", 0 en caso contrario

In [18]:
df_uncleaned.buy_box_availability = np.where(df_uncleaned.buy_box_availability != "Add to cart", 0, 1)
df_uncleaned.head()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at,has_coupon
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300,89.68,NaN,159.00,No Badge,Sponsored,Save 15% with coupon,1,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29,1
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,"2,457",6000,9.99,NaN,15.99,No Badge,Sponsored,No Coupon,1,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29,0
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,"3,044",2000,314.00,NaN,349.00,No Badge,Sponsored,No Coupon,1,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29,0
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,"35,882",10000,162.24,$162.24,162.24,Best Seller,Organic,No Coupon,0,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29,0
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,"28,988",10000,72.74,$72.74,72.74,No Badge,Organic,No Coupon,0,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29,0

In [19]:
df_uncleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      32164 non-null  Int64
 4   current/discounted_price  40613 non-null  float64
 5   price_on_variant          20071 non-null  object
 6   listed_price              40613 non-null  float64
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      42675 non-null  int32
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
 16  has_coupon                42675 non-null  int32
dtypes: Int64(1), float64(3), int32(2), object(11)
memory usage: 5.3+ MB

# DROP COLUMNS

In [20]:
df_uncleaned.drop(columns=['delivery_details', 'product_url', 'collected_at'], inplace=True)
df_uncleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      32164 non-null  Int64
 4   current/discounted_price  40613 non-null  float64
 5   price_on_variant          20071 non-null  object
 6   listed_price              40613 non-null  float64
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      42675 non-null  int32
 11  sustainability_badges     3408 non-null   object
 12  image_url                 42675 non-null  object
 13  has_coupon                42675 non-null  int32
dtypes: Int64(1), float64(3), int32(2), object(8)
memory usage: 4.3+ MB

# NUMBER OF REVIEWS

In [21]:
df_uncleaned['number_of_reviews'] = df_uncleaned['number_of_reviews'].str.replace(",", "").str.strip().astype(float)
df_uncleaned.head()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,sustainability_badges,image_url,has_coupon
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300,89.68,NaN,159.00,No Badge,Sponsored,Save 15% with coupon,1,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,1
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000,9.99,NaN,15.99,No Badge,Sponsored,No Coupon,1,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,0
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000,314.00,NaN,349.00,No Badge,Sponsored,No Coupon,1,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,0
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000,162.24,$162.24,162.24,Best Seller,Organic,No Coupon,0,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,0
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000,72.74,$72.74,72.74,No Badge,Organic,No Coupon,0,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,0

# DISCOUNT PERCENTAGE

In [ ]:
df_uncleaned['discount_percentage'] = ((df_uncleaned['listed_price'] - df_uncleaned['current/discounted_price'])/ df_uncleaned['listed_price']) * 100

df_uncleaned['discount_percentage'] = df_uncleaned['discount_percentage'].round(2)

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,sustainability_badges,image_url,has_coupon,category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,1,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,1,"Audio, Sound & Recording Gear",43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,1,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,0,"Chargers, Adapters & Cables",37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,1,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,0,"Audio, Sound & Recording Gear",10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,0,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,0,Wearables,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,0,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,0,Small Gadget Accessories (Cases & Protectors),0.00

# CATEGORIZACIÓN DE PRODUCTOS

In [ ]:
import pandas as pd
import torch
from sentence_transformers import SentenceTransformer, util
from tqdm.notebook import tqdm 
import sys

# 1. Cargar el modelo
model = SentenceTransformer('all-MiniLM-L6-v2')

# 2. Definir las categorías
candidate_labels = [
    "Laptops",
    "Mobile Cell Phones & Smartphones",
    "Tablets & E-readers (DEVICES ONLY)",
    "Small Gadget Accessories (Cases & Protectors)",
    "PC Components",
    "Computer Peripherals",
    "Audio, Sound & Recording Gear",
    "Cameras & Photography",
    "TV & Video Displays",
    "Video Game Consoles & Virtual Reality",
    "Storage & Memory Cards",
    "Power & Batteries",
    "Chargers, Adapters & Cables",
    "Networking",
    "Printers & Scanners (Hardware)",
    "Smart Home & Security",
    "Wearables",
    "Office Supplies, Ink & Toner",
    "Protection Plans",
    "Other Electronics"
]

# 3. Pre-calculamos los vectores de las categorías
label_embeddings = model.encode(candidate_labels, convert_to_tensor=True)

# 4. Cargar datos
titles = df_uncleaned['title'].fillna("Unknown").tolist()

# 5. Clasificación con barra de progreso visual
batch_size = 128  # Procesamos de 128 en 128 para mayor velocidad
all_predictions = []

print(f"Iniciando clasificación de {len(titles)} productos...")

# Usamos tqdm directamente en el rango de los lotes
for i in tqdm(range(0, len(titles), batch_size), desc="Clasificando productos"):
    batch_titles = titles[i : i + batch_size]
    
    # Generar embeddings del lote
    batch_embeddings = model.encode(batch_titles, convert_to_tensor=True, show_progress_bar=False)
    
    # Similitud de coseno 
    cosine_scores = util.cos_sim(batch_embeddings, label_embeddings)
    
    # Seleccionar la categoría con mayor puntuación
    best_matches = torch.argmax(cosine_scores, dim=1).cpu().tolist()
    
    # Guardar resultados
    batch_preds = [candidate_labels[idx] for idx in best_matches]
    all_predictions.extend(batch_preds)

# 6. Guardar y mostrar resultados
df_uncleaned['category'] = all_predictions

print("\n¡Proceso completado!")
print(df_uncleaned['category'].value_counts())

d:\Documentos\diego\Master\Amazon-Smart-Pricing\.venv\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
d:\Documentos\diego\Master\Amazon-Smart-Pricing\.venv\Lib\site-packages\huggingface_hub\file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Iniciando clasificación de 42675 productos...

Clasificando productos:   0%|          | 0/334 [00:00<?, ?it/s]

¡Proceso completado!
category
Computer Peripherals                             3517
Office Supplies, Ink & Toner                     3470
Audio, Sound & Recording Gear                    3413
PC Components                                    3280
Protection Plans                                 3068
TV & Video Displays                              2891
Wearables                                        2890
Cameras & Photography                            2871
Power & Batteries                                2767
Laptops                                          2611
Chargers, Adapters & Cables                      2494
Small Gadget Accessories (Cases & Protectors)    2405
Storage & Memory Cards                           1993
Printers & Scanners (Hardware)                    936
Other Electronics                                 903
Mobile Cell Phones & Smartphones                  870
Video Game Consoles & Virtual Reality             694
Smart Home & Security                             559
Networking                                        546
Tablets & E-readers (DEVICES ONLY)                497
Name: count, dtype: int64

In [23]:
from IPython.display import Image, HTML

# 1. Definimos una función que envuelve la URL en una etiqueta HTML <img>
def render_image(url):
    return f'<img src="{url}" width="80" >'

# 2. Seleccionamos la muestra
sample_peripherals = df_uncleaned[df_uncleaned['category'] == 'Tablets & E-readers (DEVICES ONLY)'][['title', 'image_url', 'listed_price']].sample(15)

# 3. Mostramos la tabla renderizando el HTML
# 'escape=False' permite que el navegador lea los tags <img> en lugar de verlos como texto
HTML(sample_peripherals.to_html(escape=False, formatters=dict(image_url=render_image)))

# Eliminación de características

In [24]:
df_uncleaned.drop(columns=['price_on_variant'], inplace=True)
df_uncleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         41651 non-null  float64
 3   bought_in_last_month      32164 non-null  Int64
 4   current/discounted_price  40613 non-null  float64
 5   listed_price              40613 non-null  float64
 6   is_best_seller            42675 non-null  object
 7   is_sponsored              42675 non-null  object
 8   is_couponed               42675 non-null  object
 9   buy_box_availability      42675 non-null  int32
 10  sustainability_badges     3408 non-null   object
 11  image_url                 42675 non-null  object
 12  has_coupon                42675 non-null  int32
 13  category                  42675 non-null  object
dtypes: Int64(1), float64(4), int32(2), object(7)
memory usage: 4.3+ MB

# Exportación CSV

In [25]:
df_uncleaned.to_csv('../Datasets/amazon_final.csv', index=False)